map $realip_remote_addr$remote_addr $cleansed_x_forwarded_for {
    "~^([^ ]+)\1$" "$realip_remote_addr";
    default "$http_x_forwarded_for, $realip_remote_addr";
}

server {
    server_name _;
    set_real_ip_from nginx-lab-nginx-1;
    set_real_ip_from nginx-lab-nginx-2;
    set_real_ip_from nginx-lab-nginx-3;
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;
    location / {
        default_type text/plain;
        return 200 $http_x_forwarded_for;
    }
    location ~ ^/(nginx-lab-nginx-\d+)/(.*) {
        
        proxy_set_header X-Forwarded-For $cleansed_x_forwarded_for;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        set $nexthop $1;
        set $rest $2;
        resolver 127.0.0.11 valid=30s;
        proxy_pass http://$nexthop/$rest;
    }
}
